//
//  AddVerbs.swift
//  Write-To-Realm-From-CSV
//
//  Created by Scott O'Halloran on 8/20/23.
//

import Foundation
import RealmSwift

func addVerbs(inputFile: String, itemCount: Int) {
    // open the CSV file and read line by line
    let verbList = readCSV(inputFile: inputFile, separator: "\n")
    for(verb) in verbList {
        //create array of items separated by ","
        let newVerb = verb.components(separatedBy: ",")
        let listVerb = Verb()
        //Check to see if the number of items on the line
        // being read matches the number of items in a noun
        if (newVerb.count == itemCount)
        {
            listVerb.base = newVerb[0]
            listVerb.english = newVerb[1]
            listVerb.type = newVerb[2]
            listVerb.verbalAdjective = newVerb[3]
            listVerb.verbalNoun = newVerb[4]
            listVerb.simplePast1stPersonSingularIndicative = newVerb[5]
            listVerb.simplePast1stPersonSingularInterrogative = newVerb[6]
            listVerb.simplePast1stPersonSingularNegative = newVerb[7]
            listVerb.simplePast2ndPersonSingularIndicative = newVerb[8]
            listVerb.simplePast2ndPersonSingularInterrogative = newVerb[9]
            listVerb.simplePast2ndPersonSingularNegative = newVerb[10]
            listVerb.simplePast3rdPersonSingularIndicative = newVerb[11]
            listVerb.simplePast3rdPersonSingularInterrogative = newVerb[12]
            listVerb.simplePast3rdPersonSingularNegative = newVerb[13]
            listVerb.simplePast1stPersonPluralIndicativeAlternative = newVerb[14]
            listVerb.simplePast1stPersonPluralInterrogativeAlternative = newVerb[15]
            listVerb.simplePast1stPersonPluralNegativeAlternative = newVerb[16]
            listVerb.simplePast1stPersonPluralIndicative = newVerb[17]
            listVerb.simplePast1stPersonPluralInterrogative = newVerb[18]
            listVerb.simplePast1stPersonPluralNegative = newVerb[19]
            listVerb.simplePast2ndPersonPluralIndicative = newVerb[20]
            listVerb.simplePast2ndPersonPluralInterrogative = newVerb[21]
            listVerb.simplePast2ndPersonPluralNegative = newVerb[22]
            listVerb.simplePast3rdPersonPluralIndicative = newVerb[23]
            listVerb.simplePast3rdPersonPluralInterrogative = newVerb[24]
            listVerb.simplePast3rdPersonPluralNegative = newVerb[25]
            listVerb.simplePast3rdPersonPluralIndicativeAlternative = newVerb[26]
            listVerb.simplePast3rdPersonPluralInterrogativeAlternative = newVerb[27]
            listVerb.simplePast3rdPersonPluralNegativeAlternative = newVerb[28]
            listVerb.simplePastImpersonalIndicative = newVerb[29]
            listVerb.simplePastImpersonalInterrogative = newVerb[30]
            listVerb.simplePastImpersonalNegative = newVerb[31]
            listVerb.present1stPersonSingularIndicative = newVerb[32]
            listVerb.present1stPersonSingularInterrogative = newVerb[33]
            listVerb.present1stPersonSingularNegative = newVerb[34]
            listVerb.present2ndPersonSingularIndicative = newVerb[35]
            listVerb.present2ndPersonSingularInterrogative = newVerb[36]
            listVerb.present2ndPersonSingularNegative = newVerb[37]
            listVerb.present3rdPersonSingularIndicative = newVerb[38]
            listVerb.present3rdPersonSingularInterrogative = newVerb[39]
            listVerb.present3rdPersonSingularNegative = newVerb[40]
            listVerb.present1stPersonPluralIndicativeAlternative = newVerb[41]
            listVerb.present1stPersonPluralInterrogativeAlternative = newVerb[42]
            listVerb.present1stPersonPluralNegativeAlternative = newVerb[43]
            listVerb.present1stPersonPluralIndicative = newVerb[44]
            listVerb.present1stPersonPluralInterrogative = newVerb[45]
            listVerb.present1stPersonPluralNegative = newVerb[46]
            listVerb.present2ndPersonPluralIndicative = newVerb[47]
            listVerb.present2ndPersonPluralInterrogative = newVerb[48]
            listVerb.present2ndPersonPluralNegative = newVerb[49]
            listVerb.present3rdPersonPluralIndicative = newVerb[50]
            listVerb.present3rdPersonPluralInterrogative = newVerb[51]
            listVerb.present3rdPersonPluralNegative = newVerb[52]
            listVerb.presentImpersonalIndicative = newVerb[53]
            listVerb.presentImpersonalInterrogative = newVerb[54]
            listVerb.presentImpersonalNegative = newVerb[55]
            listVerb.future1stPersonSingularIndicative = newVerb[56]
            listVerb.future1stPersonSingularInterrogative = newVerb[57]
            listVerb.future1stPersonSingularNegative = newVerb[58]
            listVerb.future2ndPersonSingularIndicative = newVerb[59]
            listVerb.future2ndPersonSingularInterrogative = newVerb[60]
            listVerb.future2ndPersonSingularNegative = newVerb[61]
            listVerb.future3rdPersonSingularIndicative = newVerb[62]
            listVerb.future3rdPersonSingularInterrogative = newVerb[63]
            listVerb.future3rdPersonSingularNegative = newVerb[64]
            listVerb.future1stPersonPluralIndicativeAlternative = newVerb[65]
            listVerb.future1stPersonPluralInterrogativeAlternative = newVerb[66]
            listVerb.future1stPersonPluralNegativeAlternative = newVerb[67]
            listVerb.future1stPersonPluralIndicative = newVerb[68]
            listVerb.future1stPersonPluralInterrogative = newVerb[69]
            listVerb.future1stPersonPluralNegative = newVerb[70]
            listVerb.future2ndPersonPluralIndicative = newVerb[71]
            listVerb.future2ndPersonPluralInterrogative = newVerb[72]
            listVerb.future2ndPersonPluralNegative = newVerb[73]
            listVerb.future3rdPersonPluralIndicative = newVerb[74]
            listVerb.future3rdPersonPluralInterrogative = newVerb[75]
            listVerb.future3rdPersonPluralNegative = newVerb[76]
            listVerb.futureImpersonalIndicative = newVerb[77]
            listVerb.futureImpersonalInterrogative = newVerb[78]
            listVerb.futureImpersonalNegative = newVerb[79]
            listVerb.conditional1stPersonSingularIndicative = newVerb[80]
            listVerb.conditional1stPersonSingularInterrogative = newVerb[81]
            listVerb.conditional1stPersonSingularNegative = newVerb[82]
            listVerb.conditional2ndPersonSingularIndicative = newVerb[83]
            listVerb.conditional2ndPersonSingularInterrogative = newVerb[84]
            listVerb.conditional2ndPersonSingularNegative = newVerb[85]
            listVerb.conditional3rdPersonSingularIndicative = newVerb[86]
            listVerb.conditional3rdPersonSingularInterrogative = newVerb[87]
            listVerb.conditional3rdPersonSingularNegative = newVerb[88]
            listVerb.conditional1stPersonPluralIndicativeAlternative = newVerb[89]
            listVerb.conditional1stPersonPluralInterrogativeAlternative = newVerb[90]
            listVerb.conditional1stPersonPluralNegativeAlternative = newVerb[91]
            listVerb.conditional1stPersonPluralIndicative = newVerb[92]
            listVerb.conditional1stPersonPluralInterrogative = newVerb[93]
            listVerb.conditional1stPersonPluralNegative = newVerb[94]
            listVerb.conditional2ndPersonPluralIndicative = newVerb[95]
            listVerb.conditional2ndPersonPluralInterrogative = newVerb[96]
            listVerb.conditional2ndPersonPluralNegative = newVerb[97]
            listVerb.conditional3rdPersonPluralIndicativeAlternative = newVerb[98]
            listVerb.conditional3rdPersonPluralInterrogativeAlternative = newVerb[99]
            listVerb.conditional3rdPersonPluralNegativeAlternative = newVerb[100]
            listVerb.conditional3rdPersonPluralIndicative = newVerb[101]
            listVerb.conditional3rdPersonPluralInterrogative = newVerb[102]
            listVerb.conditional3rdPersonPluralNegative = newVerb[103]
            listVerb.conditionalImpersonalIndicative = newVerb[104]
            listVerb.conditionalImpersonalInterrogative = newVerb[105]
            listVerb.conditionalImpersonalNegative = newVerb[106]
            listVerb.habitualPast1stPersonSingularIndicative = newVerb[107]
            listVerb.habitualPast1stPersonSingularInterrogative = newVerb[108]
            listVerb.habitualPast1stPersonSingularNegative = newVerb[109]
            listVerb.habitualPast2ndPersonSingularIndicative = newVerb[110]
            listVerb.habitualPast2ndPersonSingularInterrogative = newVerb[111]
            listVerb.habitualPast2ndPersonSingularNegative = newVerb[112]
            listVerb.habitualPast3rdPersonSingularIndicative = newVerb[113]
            listVerb.habitualPast3rdPersonSingularInterrogative = newVerb[114]
            listVerb.habitualPast3rdPersonSingularNegative = newVerb[115]
            listVerb.habitualPast1stPersonPluralIndicativeAlternative = newVerb[116]
            listVerb.habitualPast1stPersonPluralInterrogativeAlternative = newVerb[117]
            listVerb.habitualPast1stPersonPluralNegativeAlternative = newVerb[118]
            listVerb.habitualPast1stPersonPluralIndicative = newVerb[119]
            listVerb.habitualPast1stPersonPluralInterrogative = newVerb[120]
            listVerb.habitualPast1stPersonPluralNegative = newVerb[121]
            listVerb.habitualPast2ndPersonPluralIndicative = newVerb[122]
            listVerb.habitualPast2ndPersonPluralInterrogative = newVerb[123]
            listVerb.habitualPast2ndPersonPluralNegative = newVerb[124]
            listVerb.habitualPast3rdPersonPluralIndicativeAlternative = newVerb[125]
            listVerb.habitualPast3rdPersonPluralInterrogativeAlternative = newVerb[126]
            listVerb.habitualPast3rdPersonPluralNegativeAlternative = newVerb[127]
            listVerb.habitualPast3rdPersonPluralIndicative = newVerb[128]
            listVerb.habitualPast3rdPersonPluralInterrogative = newVerb[129]
            listVerb.habitualPast3rdPersonPluralNegative = newVerb[130]
            listVerb.habitualPastImpersonalIndicative = newVerb[131]
            listVerb.habitualPastImpersonalInterrogative = newVerb[132]
            listVerb.habitualPastImpersonalNegative = newVerb[133]
            listVerb.imperative1stPersonSingularIndicative = newVerb[134]
            listVerb.imperative1stPersonSingularNegative = newVerb[135]
            listVerb.imperative2ndPersonSingularIndicative = newVerb[136]
            listVerb.imperative2ndPersonSingularNegative = newVerb[137]
            listVerb.imperative3rdPersonSingularIndicative = newVerb[138]
            listVerb.imperative3rdPersonSingularNegative = newVerb[139]
            listVerb.imperative1stPersonPluralIndicative = newVerb[140]
            listVerb.imperative1stPersonPluralNegative = newVerb[141]
            listVerb.imperative1stPersonPluralIndicativeAlternative = newVerb[142]
            listVerb.imperative1stPersonPluralNegativeAlternative = newVerb[143]
            listVerb.imperative2ndPersonPluralIndicative = newVerb[144]
            listVerb.imperative2ndPersonPluralNegative = newVerb[145]
            listVerb.imperative3rdPersonPluralIndicative = newVerb[146]
            listVerb.imperative3rdPersonPluralNegative = newVerb[147]
            listVerb.imperative3rdPersonPluralIndicativeAlternative = newVerb[148]
            listVerb.imperative3rdPersonPluralNegativeAlternative = newVerb[149]
            listVerb.imperativeImpersonalIndicative = newVerb[150]
            listVerb.imperativeImpersonalNegative = newVerb[151]
            listVerb.presentSubjunctive1stPersonSingularIndicative = newVerb[152]
            listVerb.presentSubjunctive1stPersonSingularNegative = newVerb[153]
            listVerb.presentSubjunctive2ndPersonSingularIndicative = newVerb[154]
            listVerb.presentSubjunctive2ndPersonSingularNegative = newVerb[155]
            listVerb.presentSubjunctive3rdPersonSingularIndicative = newVerb[156]
            listVerb.presentSubjunctive3rdPersonSingularNegative = newVerb[157]
            listVerb.presentSubjunctive1stPersonPluralIndicative = newVerb[158]
            listVerb.presentSubjunctive1stPersonPluralNegative = newVerb[159]
            listVerb.presentSubjunctive1stPersonPluralIndicativeAlternative = newVerb[160]
            listVerb.presentSubjunctive1stPersonPluralNegativeAlternative = newVerb[161]
            listVerb.presentSubjunctive2ndPersonPluralIndicative = newVerb[162]
            listVerb.presentSubjunctive2ndPersonPluralNegative = newVerb[163]
            listVerb.presentSubjunctive3rdPersonPluralIndicative = newVerb[164]
            listVerb.presentSubjunctive3rdPersonPluralNegative = newVerb[165]
            listVerb.presentSubjunctiveImpersonalIndicative = newVerb[166]
            listVerb.presentSubjunctiveImpersonalNegative = newVerb[167]

            try! realm.write {
                realm.add(listVerb)
            }
        }
    }
}
